# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-05 09:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tld', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('cca2', models.CharField(max_length=100, null=True)),
                ('ccn3', models.CharField(max_length=100, null=True)),
                ('cioc', models.CharField(max_length=100, null=True)),
                ('independent', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=100, null=True)),
                ('unMember', models.BooleanField(default=False)),
                ('currencies', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('idd', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('capital', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('altSpellings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('subregion', models.CharField(blank=True, max_length=30, null=True)),
                ('languages', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('latlng', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('landlocked', models.BooleanField(default=False)),
                ('borders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
                ('area', models.BigIntegerField(null=True)),
                ('demonyms', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('cca3', models.CharField(max_length=100)),
                ('translations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=100, null=True)),
                ('maps', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('population', models.BigIntegerField(null=True)),
                ('gini', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('fifa', models.CharField(blank=True, max_length=10, null=True)),
                ('car', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('timezones', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('continents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('flags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('coatOfArms', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('startOfWeek', models.CharField(blank=True, max_length=20, null=True)),
                ('capitalInfo', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('postalCode', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
